NAME_MAXIMUM: 50
EMAIL_MACIMUM: 255
PASSWORD_MINIMUM: 6
check_success: "1"
check_fail: "0"
MAXSIZE: 50
PER_PAGE: 30
default_from_email: "nguyendyc95vn@gmail.com"
address: "smtp.gmail.com"
port: 587
domain: "gmail.com"
authentication: "plain"
enable_auto: true
password_expire_time: 2
