NAME_MAXIMUM: 50
EMAIL_MACIMUM: 255
PASSWORD_MINIMUM: 6
check_success: "1"
check_fail: "0"
MAXSIZE: 50
PER_PAGE: 30
default_from_email: "noreply@example.com"
address: "smtp.gmail.com"
port: 587
domain: "gmail.com"
authentication: "plain"
enable_auto: true
password_expire_time: 2
content_length: 140
index_per_page: 20
max_upload_size: 5
avatar_size: 80
avatar_small: 50
avatar_XS: 30
